# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: boot_admin
    password: bootAdmin_123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2              # 池中维护的最小空闲连接数
      maximum-pool-size: 10        # 池中维护的最大连接数
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update